services:
  finrl_service:
    image: finrl_service:latest # already built GPU image
    build:
      context: .
      dockerfile: finrl_service/Dockerfile
    runtime: nvidia
    volumes:
      - ./shared:/shared:ro
      - ./shared:/shared:ro
    environment:
      PYTHONPATH: "/shared:/app"
    network_mode: host
    ipc: host
    cpuset: "0-3"
    command:
      - /usr/bin/python3
      - /app/finrl_service/rl_agent_tick_sub.py
  execution_service:
    build:
      context: .
      dockerfile: execution_service/Dockerfile
    volumes:
      - ./shared:/shared:ro
      - ./shared:/shared:ro
    environment:
      PYTHONPATH: "/shared:/app"
    command:
      - python
      - /app/execution_service/action_server.py
    network_mode: host
    ipc: host
    cpuset: "4-7"
