services:
  api:
    build:
      context: ../
      dockerfile: backend/Dockerfile
    container_name: infra-api
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    working_dir: /app

  gradio:
    build:
      context: ../
      dockerfile: frontend/Dockerfile
    container_name: infra-gradio
    command: python gradio_app.py --headless
    ports:
      - "7860:7860"
    restart: unless-stopped
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
