version: '3.9'
services:
  app:
    build: .
    container_name: finrl-app
    ports:
      - "7860:7860" # Gradio default
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    depends_on:
      - redis
      - postgres
    volumes:
      - ../backend:/workspace/backend
      - ../frontend:/workspace/frontend
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  redis:
    image: redis:7
    container_name: finrl-redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres:15
    container_name: finrl-postgres
    environment:
      POSTGRES_USER: finrl
      POSTGRES_PASSWORD: finrlpass
      POSTGRES_DB: finrl_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: 