version: "3.8"

services:
  api:
    build:
      context: ../                # path to API Dockerfile
    container_name: infra-api
    ports:
      - "8000:8000"
    restart: unless-stopped

  gradio:
    build:
      context: ../frontend        # <── build FROM ./frontend, not repo root
      dockerfile: Dockerfile
    container_name: infra-gradio
    command: python /app/gradio_app.py --headless   # <── run the UI, not plain python
    ports:
      - "7860:7860"
    restart: unless-stopped
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
