
services:
  api:
    build: ..
  gradio:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        GRADIO_VERSION: 4.44.1
      target: gradio
    depends_on:
      - api
    container_name: infra-gradio-1
    restart: unless-stopped
    ports:
      - "7860:7860"
